export const COLLEGE_GATE = {
  id: "gate",
  label: "MUIT Main Gate",
  lat: 26.930752,
  lng: 80.928451,
  type: "user_location" as const,
  color: "#3b82f6",
};

export const CAMPUS_LOCATIONS = [
  {
    id: "admin",
    label: "Administrative Block",
    lat: 26.93015,
    lng: 80.9282,
    color: "#3b82f6",
    icon: "🏛️",
    marked: true,
    searchTerms: ["admin", "administration", "office", "block", "admission"],
  },
  {
    id: "second-gate",
    label: "Second Gate",
    lat: 26.930552,
    lng: 80.92738,
    color: "#60a5fa",
    icon: "🚪",
    marked: true,
    searchTerms: ["second gate", "gate 2", "gate", "entry", "exit", "entrance"],
  },
  {
    id: "library",
    label: "Central Library & Computer Lab",
    lat: 26.930383,
    lng: 80.92871,
    color: "#8b5cf6",
    icon: "📚",
    marked: true,
    searchTerms: [
      "library",
      "books",
      "study",
      "reading",
      "digital library",
      "central library",
      "central computer lab",
    ],
  },
  {
    id: "engineering",
    label: "Engineering Department",
    lat: 26.929442,
    lng: 80.927245,
    color: "#f59e0b",
    icon: "⚙️",
    marked: true,
    searchTerms: [
      "engineering",
      "technology",
      "btech",
      "mtech",
      "computer science",
      "cse",
      "ai",
      "ml",
      "department",
    ],
  },
  {
    id: "engineering-workshop",
    label: "Engineering Workshop",
    lat: 26.928862,
    lng: 80.927504,
    color: "#38bdf8",
    icon: "🔧",
    marked: true,
    searchTerms: ["workshop", "engineering workshop", "mechanical", "practical", "lab"],
  },
  {
    id: "canteen",
    label: "Central Canteen",
    lat: 26.93034,
    lng: 80.92746,
    color: "#22c55e",
    icon: "🍽️",
    marked: true,
    searchTerms: [
      "canteen",
      "central canteen",
      "food",
      "cafeteria",
      "mess",
      "food court",
      "snacks",
    ],
  },
  {
    id: "second-canteen",
    label: "Second Canteen",
    lat: 26.927476,
    lng: 80.929096,
    color: "#4ade80",
    icon: "☕",
    marked: true,
    searchTerms: ["second canteen", "canteen", "food", "cafeteria", "mess", "snacks"],
  },
  {
    id: "auditorium",
    label: "Auditorium",
    lat: 26.930216,
    lng: 80.927392,
    color: "#ef4444",
    icon: "🎭",
    marked: true,
    searchTerms: ["auditorium", "auditorium room", "hall", "events", "seminar", "conference"],
  },
  {
    id: "boys-hostel",
    label: "Saptarishi Boys Hostel",
    lat: 26.928464,
    lng: 80.92933,
    color: "#06b6d4",
    icon: "🏠",
    marked: true,
    searchTerms: ["hostel", "boys", "saptarishi", "accommodation", "residence", "room"],
  },
  {
    id: "girls-hostel",
    label: "Virangna Jhalkaribai Girls Hostel",
    lat: 26.930841,
    lng: 80.929224,
    color: "#ec4899",
    icon: "🏠",
    marked: true,
    searchTerms: [
      "hostel",
      "girls",
      "virangna",
      "jhalkaribai",
      "accommodation",
      "residence",
      "room",
    ],
  },
  {
    id: "playground",
    label: "Sport Ground",
    lat: 26.92926,
    lng: 80.928601,
    color: "#f97316",
    icon: "⚽",
    marked: true,
    searchTerms: [
      "playground",
      "sport ground",
      "sports",
      "ground",
      "cricket",
      "football",
      "basketball",
      "gym",
    ],
  },
  {
    id: "computer-lab",
    label: "Computer Lab",
    lat: 26.929652,
    lng: 80.927498,
    color: "#14b8a6",
    icon: "💻",
    marked: true,
    searchTerms: ["computer", "lab", "labs", "coding", "programming", "it lab"],
  },
  {
    id: "programming-lab",
    label: "Programming Lab",
    lat: 26.929569,
    lng: 80.927498,
    color: "#2dd4bf",
    icon: "⌨️",
    marked: true,
    searchTerms: ["programming", "programming lab", "coding", "software", "development"],
  },
  {
    id: "pharmacy",
    label: "School of Pharmaceutical Sciences",
    lat: 26.930018,
    lng: 80.927964,
    color: "#a855f7",
    icon: "💊",
    marked: true,
    searchTerms: ["pharmacy", "pharmaceutical", "pharmaceutical sciences", "pharma", "medicine"],
  },
  {
    id: "chancellors-house",
    label: "Chancellor's House",
    lat: 26.929329,
    lng: 80.929182,
    color: "#fb7185",
    icon: "🏛️",
    marked: true,
    searchTerms: ["chancellor", "chancellor house", "chancellors", "vc", "vice chancellor"],
  },
  {
    id: "commerce",
    label: "School of Commerce & Management",
    lat: 26.93,
    lng: 80.92925,
    color: "#eab308",
    icon: "📊",
    marked: true,
    searchTerms: ["commerce", "management", "mba", "bba", "business"],
  },
  {
    id: "science",
    label: "School of Science",
    lat: 26.92965,
    lng: 80.92775,
    color: "#6366f1",
    icon: "🔬",
    marked: true,
    searchTerms: ["science", "physics", "chemistry", "mathematics", "biology"],
  },
  {
    id: "humanities",
    label: "School of Humanities & Arts",
    lat: 26.927134,
    lng: 80.929327,
    color: "#d946ef",
    icon: "🎨",
    marked: true,
    searchTerms: [
      "humanities",
      "humentic",
      "arts",
      "english",
      "hindi",
      "journalism",
      "media",
      "department",
    ],
  },
  {
    id: "parking",
    label: "Parking Area",
    lat: 26.930023,
    lng: 80.928573,
    color: "#78716c",
    icon: "🅿️",
    marked: true,
    searchTerms: ["parking", "car", "bike", "vehicle", "park"],
  },
] as const;
