import type { LucideIcon } from "lucide-react";
import {
  Building2,
  BookOpen,
  Cog,
  Wrench,
  UtensilsCrossed,
  Coffee,
  Theater,
  Home,
  Volleyball,
  Monitor,
  Code,
  FlaskConical,
  Briefcase,
  GraduationCap,
  Palette,
  Car,
  DoorOpen,
  Landmark,
} from "lucide-react";

export const LOCATION_ICONS: Record<string, LucideIcon> = {
  admin:       Building2,
  "second-gate": DoorOpen,
  library:     BookOpen,
  engineering: Cog,
  "engineering-workshop": Wrench,
  canteen:     UtensilsCrossed,
  "second-canteen": Coffee,
  auditorium:  Theater,
  "boys-hostel":  Home,
  "girls-hostel": Home,
  playground:  Volleyball,
  "computer-lab": Monitor,
  "programming-lab": Code,
  pharmacy:    FlaskConical,
  "chancellors-house": Landmark,
  commerce:    Briefcase,
  science:     GraduationCap,
  humanities:  Palette,
  parking:     Car,
};
